version: '2'

services:
  janus-gateway:
    image: janus-gateway
    ports:
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
    volumes:
      - ./conf:/opt/janus/etc/janus
  nginx:
    image: nginx:1.14.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443" # 나중에 https 등록하면 이 포트 사용함
      - "7088:7088"
      - "8088:8088"
      - "8089:8089"
      - "8188:8188"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/skswlsaks/Desktop/ssl:/ssl

    depends_on:
      - janus-gateway
